export const useStyles = (mobileSize, color) => ({
  body: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  textDate: {
    fontSize: 11,
    color: 'black',
  },
  textDateSelected: {
    fontSize: 11,
    color: 'white',
  },
  textApply: {
    color: 'white',
    fontSize: 12,
  },
  textClose: {
    fontSize: 12,
  },
  circle: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 30,
    height: 30,
  },
  circleActive: {
    display: 'flex',
    width: 30,
    height: 30,
    backgroundColor: color.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    color: 'white',
  },
  itemDDMMYY: {
    color: 'black',
    fontSize: mobileSize ? '11px' : '13px',
    paddingLeft: '10px',
    paddingRight: '10px',
  },
  circleActiveForDDMMYY: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '40px',
    height: '40px',
    backgroundColor: color.primary,
    borderRadius: '100%',
    color: 'white',
    fontSize: mobileSize ? '11px' : '13px',
    marginLeft: '4px',
    marginRight: '4px',
  },
  styleDate: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '5px',
  },
  buttonCancel: {
    backgroundColor: 'white',
    border: `1px solid ${color.primary}`,
    color: color.primary,
    width: '48%',
    padding: '6px 0px',
    borderRadius: '10px',
    fontSize: '12px',
  },
  buttonConfirm: {
    color: 'white',
    width: '48%',
    padding: '6px 0px',
    borderRadius: '10px',
    fontSize: '12px',
  },
  buttonDate: {
    color: color.primary,
    border: `1px solid ${color.primary}`,
    backgroundColor: 'white',
    '&:hover': { color: 'gray' },
    fontSize: mobileSize ? '11px' : '13px',
    height: '30px',
    width: '30px',
  },
  buttonDateActive: {
    backgroundColor: color.primary,
    color: 'white',
    border: `1px solid ${color.primary}`,
    '&:hover': { color: 'gray' },
    fontSize: mobileSize ? '11px' : '13px',
    width: '30px',
    height: '30px',
  },
  gridMonth: {
    display: 'grid',
    gridAutoColumns: '1fr',
    gridAutoRows: '1fr',
    gridTemplateColumns: '1fr 1fr 1fr',
    gridTemplateRows: '1fr 1fr 1fr',
    alignItems: 'center',
    justifyItems: 'center',
  },
  wrapListDate: {
    display: 'flex',
    overflowX: 'auto',
    width: '100%',
    '&::-webkit-scrollbar': { width: '0.4em' },
    '&::-webkit-scrollbar-track': {
      boxShadow: 'inset 0 0 6px rgba(0,0,0,0.00)',
      webkitBoxShadow: 'inset 0 0 6px rgba(0,0,0,0.00)',
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: 'rgba(0,0,0,.1)',
      outline: '1px solid slategrey',
    },
  },
  listDate: {
    width: '80px',
    height: '100px',
    border: '1px solid rgb(212 212 216)',
    borderRadius: '10px',
    color: '#4D86A0',
    cursor: 'pointer',
  },
  listDateActive: {
    width: '80px',
    height: '100px',
    border: '1px solid rgba(77, 134, 160, 0.5)',
    borderRadius: '10px',
    color: 'white',
    cursor: 'pointer',
    backgroundColor: '#4D86A0',
  },
  circleDate: {
    display: 'flex',
    width: 26,
    height: 26,
    backgroundColor: 'gray',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    color: 'white',
    opacity: 0.5,
  },
  circleDateActive: {
    display: 'flex',
    width: 26,
    height: 26,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    color: '#4D86A0',
  },

  wrapSeeMoreDate: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
  },
  wrapListTextAvailabel: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrapTextNotAvailable: {
    width: 26,
    height: 26,
    backgroundColor: `${color.primary}90`,
    borderRadius: 5,
    opacity: 0.3,
  },
  wrapTextAvailable: {
    width: 26,
    height: 26,
    borderRadius: 5,
    opacity: 0.3,
    border: `2px solid ${color.primary}`,
  },
  wrapTextChoosenDate: {
    width: 26,
    height: 26,
    backgroundColor: color.primary,
    borderRadius: 5,
  },
  wrapTimeDropDown: {
    border: '1px solid rgb(212 212 216)',
    width: '100%',
    display: 'flex',
    flexDirection: 'flex-column',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '5px',
  },
  wrapperMonthSlider: {
    width: '100%',
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gridTemplateRows: '1fr',
    gap: '0px 0px',
    gridAutoFlow: 'row',
    gridTemplateAreas: '". . ."',
    justifyItems: 'center',
    alignItems: 'center',
  },
  wrapperYearSlider: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  wrapperChooseDate: {
    backgroundColor: `${color.primary}20`,
    borderRadius: '5px',
    padding: '10px',
    textChoosenDate: {
      marginLeft: '5px',
      fontWeight: 'bold',
      fontSize: mobileSize ? '10px' : '13px',
    },
  },
  wrapperDeliveryDate: {
    display: 'flex',
    width: '100%',
    justifyContent: 'space-between',
  },
  wrapperChooseDateTime: {
    backgroundColor: `${color.primary}20`,
    borderRadius: '5px',
    padding: '5px',
  },
  textChooseDateTime: {
    fontWeight: 'bold',
    color: color.primary,
    fontSize: '13px',
    marginLeft: '2px',
    marginRight: '2px',
  },
});
